/**** user ****/

export const GET_ALL_USERS = 'GET_ALL_USERS'
export const SET_USER_SEARCH = 'SET_USER_SEARCH'
export const CLEAR_USER_SEARCH = 'CLEAR_USER_SEARCH'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOGOUT = 'LOGOUT'

/**** connection ****/

export const SET_CONNECTIONS = 'SET_CONNECTIONS'
export const REQUEST_CONNECTION = 'REQUEST_CONNECTION'
export const ACCEPT_CONNECTION = 'ACCEPT_CONNECTION'
export const REJECT_CONNECTION = 'REJECT_CONNECTION'